project_name: soba

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy
builds:
- id: soba
  binary: soba
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  flags:
    - -trimpath
  ldflags:
    - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"
  ignore:
    - goos: darwin
      goarch: arm
  hooks:
    post:
      - |
        sh -c '
        cat > /tmp/soba_gon_arm64.hcl << EOF
        source = ["./dist/soba-darwin-arm64/soba"]
        bundle_id = "uk.co.lessknown.soba"
        apple_id {
          username = "jon@lessknown.co.uk"
          password = "@env:AC_PASSWORD"
        }
        sign {
          application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
         }
        zip {
          output_path = "./dist/soba_darwin_arm64.zip"
        }
        EOF
        gon /tmp/soba_gon_arm64.hcl
        '
      - |
        sh -c '
        cat > /tmp/soba_gon_amd64.hcl << EOF
        source = ["./dist/soba-darwin-amd64/soba"]
        bundle_id = "uk.co.lessknown.soba"
        apple_id {
          username = "jon@lessknown.co.uk"
          password = "@env:AC_PASSWORD"
        }
        sign {
          application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
        }
        zip {
          output_path = "./dist/soba_darwin_amd64.zip"
        }
        EOF
        gon /tmp/soba_gon_amd64.hcl
        '
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ end }}"
  replacements:
    linux: Linux
    windows: Windows
    amd64: x86_64
  builds:
    - soba
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*

#         sh -c '
#         cat > /tmp/soba-gon-arm64.hcl << EOF
#         source = ["./dist/soba_darwin_arm64/soba"]
#         bundle_id = "uk.co.lessknown.soba"
#         apple_id {
#           username = "jon@lessknown.co.uk"
#           password = "@env:AC_PASSWORD"
#         }
#         sign {
#           application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
#         }
#         zip {
#           output_path = "./dist/soba_macos_arm64.zip"
#         }
#         EOF
#         gon /tmp/soba-gon.hcl
#         '
#


release:
  github:
    owner: jonhadfield
    name: soba
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
   - glob: ./dist/soba_darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
    - README
    - test
    - ignore

checksum:
  name_template: 'checksums.txt'