name: "Trivy Code Scan"

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
  watch:
    types: [started]

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

#      - name: Build an image from Dockerfile
#        run: |
#          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
#
#      - name: Run Trivy vulnerability scanner in docker mode
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
#          format: 'template'
#          template: '@/contrib/sarif.tpl'
#          output: 'trivy-results-docker.sarif'
#          severity: 'CRITICAL'
#
#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: 'trivy-results-docker.sarif'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: DEBUG Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4
        with:
          sarif_file: 'trivy-results.sarif'
